// <auto-generated />
using System;
using CinemaManagement.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaManagement.API.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    partial class CinemaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaManagement.API.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int");

                    b.Property<int>("ShowtimeID")
                        .HasColumnType("int");

                    b.Property<int?>("ShowtimeID1")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("BookingID");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("MemberID");

                    b.HasIndex("ShowtimeID");

                    b.HasIndex("ShowtimeID1");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.BookingDetail", b =>
                {
                    b.Property<int>("BookingDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingDetailID"));

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SeatID")
                        .HasColumnType("int");

                    b.HasKey("BookingDetailID");

                    b.HasIndex("BookingID");

                    b.HasIndex("SeatID");

                    b.ToTable("BookingDetails");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreID"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GenreID");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreID = 1,
                            GenreName = "Hanh dong"
                        },
                        new
                        {
                            GenreID = 2,
                            GenreName = "Hai"
                        },
                        new
                        {
                            GenreID = 3,
                            GenreName = "Tam ly"
                        },
                        new
                        {
                            GenreID = 4,
                            GenreName = "Kinh di"
                        });
                });

            modelBuilder.Entity("CinemaManagement.API.Models.Hall", b =>
                {
                    b.Property<int>("HallID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HallID"));

                    b.Property<string>("HallName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RowsCount")
                        .HasColumnType("int");

                    b.Property<int>("SeatsPerRow")
                        .HasColumnType("int");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("HallID");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            HallID = 1,
                            HallName = "Phong 1",
                            RowsCount = 8,
                            SeatsPerRow = 10,
                            TotalSeats = 80
                        },
                        new
                        {
                            HallID = 2,
                            HallName = "Phong 2",
                            RowsCount = 6,
                            SeatsPerRow = 10,
                            TotalSeats = 60
                        });
                });

            modelBuilder.Entity("CinemaManagement.API.Models.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MembershipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TierID")
                        .HasColumnType("int");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("MemberID");

                    b.HasIndex("MembershipCode")
                        .IsUnique();

                    b.HasIndex("TierID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.MembershipTier", b =>
                {
                    b.Property<int>("TierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TierID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MinPoints")
                        .HasColumnType("int");

                    b.Property<decimal>("PointRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TierID");

                    b.ToTable("MembershipTiers");

                    b.HasData(
                        new
                        {
                            TierID = 1,
                            Description = "Hang co ban",
                            DiscountPercent = 0m,
                            MinPoints = 0,
                            PointRate = 1m,
                            TierName = "Silver"
                        },
                        new
                        {
                            TierID = 2,
                            Description = "Hang vang - giam 5%",
                            DiscountPercent = 5m,
                            MinPoints = 500,
                            PointRate = 1.5m,
                            TierName = "Gold"
                        },
                        new
                        {
                            TierID = 3,
                            Description = "Hang bach kim - giam 10%",
                            DiscountPercent = 10m,
                            MinPoints = 2000,
                            PointRate = 2m,
                            TierName = "Platinum"
                        });
                });

            modelBuilder.Entity("CinemaManagement.API.Models.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieID"));

                    b.Property<string>("AgeRating")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("GenreID")
                        .HasColumnType("int");

                    b.Property<int?>("GenreID1")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MovieID");

                    b.HasIndex("GenreID");

                    b.HasIndex("GenreID1");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.PointTransaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int?>("MemberID1")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TransactionID");

                    b.HasIndex("MemberID");

                    b.HasIndex("MemberID1");

                    b.ToTable("PointTransactions");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.Seat", b =>
                {
                    b.Property<int>("SeatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatID"));

                    b.Property<int>("HallID")
                        .HasColumnType("int");

                    b.Property<int?>("HallID1")
                        .HasColumnType("int");

                    b.Property<string>("RowLabel")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SeatID");

                    b.HasIndex("HallID");

                    b.HasIndex("HallID1");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.Showtime", b =>
                {
                    b.Property<int>("ShowtimeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShowtimeID"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HallID")
                        .HasColumnType("int");

                    b.Property<int?>("HallID1")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int?>("MovieID1")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ShowtimeID");

                    b.HasIndex("HallID");

                    b.HasIndex("HallID1");

                    b.HasIndex("MovieID");

                    b.HasIndex("MovieID1");

                    b.ToTable("Showtimes");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@cinema.local",
                            FullName = "Quan tri vien",
                            IsActive = true,
                            PasswordHash = "$2a$11$7YhtIqvUwLJTDZdlwx9DCOv4So3OEwPCmIsS/hisN/P6HjVigKsRi",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("CinemaManagement.API.Models.Booking", b =>
                {
                    b.HasOne("CinemaManagement.API.Models.Member", "Member")
                        .WithMany("Bookings")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CinemaManagement.API.Models.Showtime", "Showtime")
                        .WithMany()
                        .HasForeignKey("ShowtimeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaManagement.API.Models.Showtime", null)
                        .WithMany("Bookings")
                        .HasForeignKey("ShowtimeID1");

                    b.Navigation("Member");

                    b.Navigation("Showtime");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.BookingDetail", b =>
                {
                    b.HasOne("CinemaManagement.API.Models.Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaManagement.API.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.Member", b =>
                {
                    b.HasOne("CinemaManagement.API.Models.MembershipTier", "Tier")
                        .WithMany("Members")
                        .HasForeignKey("TierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaManagement.API.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("CinemaManagement.API.Models.Member", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.Movie", b =>
                {
                    b.HasOne("CinemaManagement.API.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CinemaManagement.API.Models.Genre", null)
                        .WithMany("Movies")
                        .HasForeignKey("GenreID1");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.PointTransaction", b =>
                {
                    b.HasOne("CinemaManagement.API.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaManagement.API.Models.Member", null)
                        .WithMany("PointTransactions")
                        .HasForeignKey("MemberID1");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.Seat", b =>
                {
                    b.HasOne("CinemaManagement.API.Models.Hall", "Hall")
                        .WithMany()
                        .HasForeignKey("HallID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaManagement.API.Models.Hall", null)
                        .WithMany("Seats")
                        .HasForeignKey("HallID1");

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.Showtime", b =>
                {
                    b.HasOne("CinemaManagement.API.Models.Hall", "Hall")
                        .WithMany()
                        .HasForeignKey("HallID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaManagement.API.Models.Hall", null)
                        .WithMany("Showtimes")
                        .HasForeignKey("HallID1");

                    b.HasOne("CinemaManagement.API.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaManagement.API.Models.Movie", null)
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieID1");

                    b.Navigation("Hall");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.Booking", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.Hall", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.Member", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("PointTransactions");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.MembershipTier", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.Movie", b =>
                {
                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("CinemaManagement.API.Models.Showtime", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
